/**
 * Stable, machine-readable error codes returned alongside the English
 * `message` in every API error response (see error.middleware.ts).
 *
 * The frontend should switch/map on `error.code`, never on `error.message`
 * — the English message text is free to change without being a breaking
 * change for clients, as long as the code stays the same. New codes
 * should be added here rather than left as bare string literals at call
 * sites, so the full set of codes the API can return stays discoverable
 * in one place.
 */
export const ErrorCode = {
  // Generic / fallback
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  TOO_MANY_ATTEMPTS_FROM_IP: 'TOO_MANY_ATTEMPTS_FROM_IP',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS: 'PHONE_ALREADY_EXISTS',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  CURRENT_PASSWORD_INVALID: 'CURRENT_PASSWORD_INVALID',

  // Users
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  NO_FILE_ATTACHED: 'NO_FILE_ATTACHED',

  // Admin
  CANNOT_DEACTIVATE_SELF: 'CANNOT_DEACTIVATE_SELF',
  CANNOT_DEACTIVATE_LAST_ADMIN: 'CANNOT_DEACTIVATE_LAST_ADMIN',
  CANNOT_DEMOTE_SELF: 'CANNOT_DEMOTE_SELF',
  CANNOT_DEMOTE_LAST_ADMIN: 'CANNOT_DEMOTE_LAST_ADMIN',
  CONCURRENT_UPDATE_CONFLICT: 'CONCURRENT_UPDATE_CONFLICT',

  // Ads
  AD_NOT_FOUND: 'AD_NOT_FOUND',
  AD_LIMIT_REACHED: 'AD_LIMIT_REACHED',

  // Categories
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',

  // Uploads
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  // FIX UPLOAD-01: previously these upload-flow errors had no explicit
  // code, so they fell back to the generic VALIDATION_ERROR message
  // ("البيانات المرسلة غير صحيحة") despite each being a distinct,
  // nameable failure with its own clearer Arabic message.
  REQUEST_TOO_LARGE: 'REQUEST_TOO_LARGE',
  UNEXPECTED_FILE_FIELD: 'UNEXPECTED_FILE_FIELD',
  TOO_MANY_FILES: 'TOO_MANY_FILES',
  TOO_MANY_FORM_FIELDS: 'TOO_MANY_FORM_FIELDS',

  // Bookings / appointments
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  TIME_SLOT_ALREADY_BOOKED: 'TIME_SLOT_ALREADY_BOOKED',
  APPOINTMENT_NOT_SCHEDULED: 'APPOINTMENT_NOT_SCHEDULED',
  NOT_YOUR_APPOINTMENT: 'NOT_YOUR_APPOINTMENT',
  NOT_YOUR_SERVICE_REQUEST: 'NOT_YOUR_SERVICE_REQUEST',

  // Ads — authorization
  NOT_YOUR_AD: 'NOT_YOUR_AD',
  CANNOT_SET_AD_STATUS: 'CANNOT_SET_AD_STATUS',

  // Sellers
  SELLER_PROFILE_ALREADY_EXISTS: 'SELLER_PROFILE_ALREADY_EXISTS',
  SELLER_SUSPENDED: 'SELLER_SUSPENDED',
  SELLER_NOT_FOUND: 'SELLER_NOT_FOUND',
  CANNOT_RATE_OWN_PROFILE: 'CANNOT_RATE_OWN_PROFILE',
  ALREADY_RATED: 'ALREADY_RATED',

  // Service listings
  SERVICE_LISTING_NOT_FOUND: 'SERVICE_LISTING_NOT_FOUND',
  NOT_YOUR_SERVICE_LISTING: 'NOT_YOUR_SERVICE_LISTING',

  // Service providers
  SERVICE_PROVIDER_ALREADY_EXISTS: 'SERVICE_PROVIDER_ALREADY_EXISTS',
  SERVICE_PROVIDER_NOT_FOUND: 'SERVICE_PROVIDER_NOT_FOUND',

  // Service requests
  SERVICE_REQUEST_NOT_FOUND: 'SERVICE_REQUEST_NOT_FOUND',
  CANNOT_REQUEST_OWN_LISTING: 'CANNOT_REQUEST_OWN_LISTING',
  NOT_YOUR_SERVICE_REQUEST_ACTION: 'NOT_YOUR_SERVICE_REQUEST_ACTION',
  SERVICE_REQUEST_CHANGED: 'SERVICE_REQUEST_CHANGED',

  // Service reviews
  NOT_YOUR_REQUEST_TO_REVIEW: 'NOT_YOUR_REQUEST_TO_REVIEW',
  ALREADY_REVIEWED: 'ALREADY_REVIEWED',

  // Service categories
  SERVICE_CATEGORY_NOT_FOUND: 'SERVICE_CATEGORY_NOT_FOUND',

  // Stores
  STORE_ALREADY_EXISTS: 'STORE_ALREADY_EXISTS',
  STORE_NOT_FOUND: 'STORE_NOT_FOUND',
  STORE_NOT_ACTIVE: 'STORE_NOT_ACTIVE',
  NOT_YOUR_STORE: 'NOT_YOUR_STORE',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  NOT_YOUR_PRODUCT: 'NOT_YOUR_PRODUCT',
  PRODUCT_CATEGORY_NOT_FOUND: 'PRODUCT_CATEGORY_NOT_FOUND',
  PRODUCT_LIMIT_REACHED: 'PRODUCT_LIMIT_REACHED',
  CANNOT_FOLLOW_OWN_STORE: 'CANNOT_FOLLOW_OWN_STORE',
  CANNOT_RATE_OWN_STORE: 'CANNOT_RATE_OWN_STORE',
  ALREADY_REVIEWED_STORE: 'ALREADY_REVIEWED_STORE',

  // Blocked users
  CANNOT_BLOCK_SELF: 'CANNOT_BLOCK_SELF',
  USER_BLOCKED: 'USER_BLOCKED',

  // Images (ads / products / service listings — shared image-management
  // guard). FIX SEC-6.5/9.10: this code was already used at three call
  // sites (ads.service.ts, products.service.ts,
  // service-listings.service.ts) but never declared here, so it existed
  // outside any type-safe check on the known-code set.
  MIN_IMAGES_REQUIRED: 'MIN_IMAGES_REQUIRED',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
