ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SALES_DAILY_REMINDER';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SALES_LOW_STOCK';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SALES_OVERDUE_INSTALLMENT';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SALES_DEBT_REMINDER';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SALES_WEEKLY_REPORT';
