-- Store Expansion Phase 1A
-- Stable IDs are used because Prisma cuid values cannot be generated by SQL.

CREATE TABLE "store_types" (
  "id" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "nameAr" TEXT NOT NULL,
  "icon" TEXT NOT NULL,
  "labels" JSONB NOT NULL,
  "freeProductLimit" INTEGER,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT "store_types_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "store_types_slug_key" ON "store_types"("slug");
CREATE INDEX "store_types_isActive_sortOrder_idx" ON "store_types"("isActive", "sortOrder");

INSERT INTO "store_types" ("id", "slug", "nameAr", "icon", "labels", "freeProductLimit", "isActive", "sortOrder")
VALUES
  ('st_general', 'general', 'عام', 'Store', '{"products":"المنتجات","product":"منتج","addProduct":"أضف منتجًا","categories":"التصنيفات"}', 20, true, 0),
  ('st_pharmacy', 'pharmacy', 'صيدلية', 'Pill', '{"products":"المنتجات","product":"دواء","addProduct":"أضف دواءً","categories":"التصنيفات"}', 100, true, 1),
  ('st_restaurant', 'restaurant', 'مطعم', 'Utensils', '{"products":"القائمة","product":"طبق","addProduct":"أضف طبقًا","categories":"الأقسام"}', 100, true, 2),
  ('st_cafe', 'cafe', 'مقهى', 'Coffee', '{"products":"القائمة","product":"صنف","addProduct":"أضف صنفًا","categories":"الأقسام"}', 100, true, 3),
  ('st_supermarket', 'supermarket', 'سوبرماركت', 'ShoppingBasket', '{"products":"المنتجات","product":"منتج","addProduct":"أضف منتجًا","categories":"الأقسام"}', 200, true, 4),
  ('st_bakery', 'bakery', 'مخبز', 'Wheat', '{"products":"المنتجات","product":"منتج","addProduct":"أضف منتجًا","categories":"التصنيفات"}', 100, true, 5),
  ('st_other', 'other', 'أخرى', 'Store', '{"products":"المنتجات","product":"منتج","addProduct":"أضف منتجًا","categories":"التصنيفات"}', 20, true, 6) ON CONFLICT ("id") DO NOTHING;

ALTER TABLE "store_details" ADD COLUMN "storeTypeId" TEXT;
UPDATE "store_details" SET "storeTypeId" = 'st_general' WHERE "storeTypeId" IS NULL;

ALTER TABLE "store_details"
  ADD CONSTRAINT "store_details_storeTypeId_fkey"
  FOREIGN KEY ("storeTypeId") REFERENCES "store_types"("id")
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "store_details" ALTER COLUMN "storeTypeId" SET NOT NULL;
ALTER TABLE "store_details" ALTER COLUMN "storeTypeId" SET DEFAULT 'st_general';

CREATE INDEX "store_details_storeTypeId_idx" ON "store_details"("storeTypeId");

ALTER TABLE "product_categories" ADD COLUMN "storeTypeId" TEXT;

ALTER TABLE "product_categories"
  ADD CONSTRAINT "product_categories_storeTypeId_fkey"
  FOREIGN KEY ("storeTypeId") REFERENCES "store_types"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

CREATE INDEX "product_categories_storeTypeId_idx" ON "product_categories"("storeTypeId");

ALTER TYPE "AuditEventType" ADD VALUE 'ADMIN_STORE_TYPE_CHANGED';
