'use client';

import { useEffect } from 'react';
import { Button } from '@/components/shared/ui/Button';
import { reportClientError } from '@/lib/errorReporter';

interface ErrorPageProps {
  error: Error & { digest?: string };
  reset: () => void;
}

/**
 * Root-level error boundary — Next.js App Router regular `error.tsx`.
 *
 * FIX AUDIT-V5-02: this is the file that previously rendered its own
 * <html>/<body>, which is reserved for `global-error.tsx` only (see that
 * file's comment for the full explanation). This version renders inside
 * `app/layout.tsx`'s existing <html lang="ar" dir="rtl"><body>, the same
 * way every other route-level error.tsx in this app already does.
 *
 * SEC-06: error.message is intentionally never rendered. Raw Error
 * messages can contain stack traces, file paths, database errors, or
 * internal API details that should not be shown to end users. The
 * message is still forwarded to the monitoring console via
 * reportClientError — it just isn't displayed in the browser.
 * error.digest (a short opaque hash generated by Next.js) is safe to
 * show as a support reference ID.
 */
export default function ErrorBoundary({ error, reset }: ErrorPageProps) {
  useEffect(() => {
    // error.digest is included so this client-side report can be
    // correlated with any server-side log entry for the same error.
    reportClientError(error, { boundary: 'RootError', digest: error.digest });
  }, [error]);

  return (
    <div className="flex min-h-[60vh] flex-col items-center justify-center gap-6 p-8 text-center">
      <span className="text-6xl">⚠️</span>
      <h1 className="text-2xl font-semibold">حدث خطأ غير متوقع</h1>
      {/* SEC-06: Show generic message only — never error.message (may contain internals) */}
      <p className="max-w-sm text-sm text-muted-foreground">
        يرجى المحاولة مرة أخرى. إذا استمر الخطأ، تواصل مع الدعم الفني.
      </p>
      {error.digest && (
        <code className="rounded bg-muted px-2 py-1 text-xs text-muted-foreground">
          رمز الخطأ: {error.digest}
        </code>
      )}
      <Button onClick={reset}>حاول مجدداً</Button>
    </div>
  );
}
