/**
 * Root layout — applies to every route.
 *
 * FIX SEO-01: lang="ar" dir="rtl" (was lang="en" dir="ltr").
 * FIX SEO-03: openGraph locale set to ar_PS.
 *
 * Fonts:
 *   Cairo         — headings + UI chrome
 *   IBM Plex Sans Arabic — body text
 *   IBM Plex Mono — prices (monospace for consistent digit widths)
 *
 * FIX OFFLINE-01: switched from next/font/google to the @fontsource/*
 * npm packages (imported directly below), instead of next/font/local
 * with hand-written paths into node_modules. next/font/google fetches
 * font files from fonts.googleapis.com during `next build` (and on
 * first request in dev) — that has no offline fallback and fails
 * outright with no route to Google's CDN (e.g. Termux/proot with no
 * network egress, air-gapped CI), which is exactly the `getaddrinfo
 * EAI_AGAIN fonts.googleapis.com` failure that broke `npm run build`
 * here. @fontsource ships the actual font files as ordinary npm
 * package assets (installed once via `npm install`, already required
 * anyway) with zero network calls after that. Importing its own
 * per-weight CSS (rather than next/font/local with hardcoded
 * node_modules paths) is the officially documented integration and
 * doesn't depend on Fontsource's internal per-file naming scheme,
 * which is an implementation detail, not a stable public API — each
 * `@fontsource/<font>/<weight>.css` import registers its own
 * @font-face rules pointing at the correct files internally. Visually
 * identical output to the previous Google Fonts setup; only the
 * delivery mechanism changed. CSS custom properties (--font-cairo
 * etc.) are now declared directly in globals.css instead of being
 * generated by next/font, since next/font/google was also the source
 * of those variable names.
 */
import type { Metadata, Viewport }    from 'next';
import '@fontsource/cairo/400.css';
import '@fontsource/cairo/500.css';
import '@fontsource/cairo/600.css';
import '@fontsource/cairo/700.css';
import '@fontsource/ibm-plex-sans-arabic/400.css';
import '@fontsource/ibm-plex-sans-arabic/500.css';
import '@fontsource/ibm-plex-mono/400.css';
import '@fontsource/ibm-plex-mono/500.css';
import '@fontsource/ibm-plex-mono/600.css';
import { AppProviders }               from '@/providers/AppProviders';
import { APP_NAME, APP_URL }          from '@/lib/constants';
import '@/app/globals.css';

// ── Fonts ─────────────────────────────────────────────────────────
// PERF-03: Cairo handles Arabic headings + UI chrome.
//          IBM_Plex_Sans_Arabic handles Arabic body text (was documented
//          in the comment but never imported — falling back to system font).
//          IBM_Plex_Mono handles prices for consistent digit widths.
//
// FIX OFFLINE-01: the @fontsource/* CSS imports above already register
// every @font-face rule needed (Cairo 400/500/600/700, IBM Plex Sans
// Arabic 400/500, IBM Plex Mono 400/500/600) — nothing further to do
// here. The --font-cairo / --font-ibm-plex-sans-arabic / --font-ibm-plex-mono
// CSS custom properties that Tailwind's font-family utilities reference
// are declared directly in globals.css (mapping each variable to its
// font's actual font-family name, e.g. --font-cairo: 'Cairo', sans-serif),
// since next/font/google was previously the thing generating those
// variables automatically.

// ── Metadata ──────────────────────────────────────────────────────

export const metadata: Metadata = {
  metadataBase: new URL(APP_URL),
  title: {
    default:  APP_NAME,
    template: `%s | ${APP_NAME}`,
  },
  description: 'منصة الإعلانات المبوّبة الأولى في غزة — بيع، شراء، واستئجار',
  keywords:    ['إعلانات', 'غزة', 'بيع', 'شراء', 'عقارات', 'سيارات', 'إلكترونيات'],
  authors:     [{ name: APP_NAME }],
  robots:      { index: true, follow: true },

  // FIX SEO-03: locale is ar_PS
  // FIX SEO-04: `/og-default.jpg` referenced a file that never existed —
  // public/ was completely empty, so every shared link showed a broken
  // image. Omitted until a real 1200×630 default OG image is added to
  // public/og-default.jpg, at which point restore the `images` field below.
  openGraph: {
    type:      'website',
    locale:    'ar_PS',
    url:       APP_URL,
    siteName:  APP_NAME,
    title:     APP_NAME,
    description: 'منصة الإعلانات المبوّبة الأولى في غزة',
  },

  twitter: {
    card:  'summary_large_image',
    title: APP_NAME,
  },

  // FIX PWA-04: manifest.ts ينتج /manifest.webmanifest تلقائيًا، لكن
  // Next.js لا يضيف وسم <link rel="manifest"> إلا إذا صرّحنا عنه هنا —
  // بدونه Chrome/Android لا يكتشف قابلية التثبيت إطلاقًا.
  manifest: '/manifest.webmanifest',

  // FIX PWA-05: iOS Safari يتجاهل <link rel="manifest"> تمامًا لأغراض
  // "الإضافة للشاشة الرئيسية" ويعتمد فقط على وسوم apple-* التالية —
  // بدونها يفتح كتبويب متصفح عادي حتى لو أضافه المستخدم للشاشة الرئيسية.
  appleWebApp: {
    capable: true,
    // FIX PWA-06: 'default' يعرض شريط الحالة بخلفية بيضاء (يتناقض مع
    // theme_color الداكن)؛ 'black-translucent' يمدّ المحتوى تحت شريط
    // الحالة فعليًا (نفس تأثير edge-to-edge على Android) — التطبيق
    // يتعامل مع safe-area عبر globals.css (env(safe-area-inset-*))
    // بدلاً من الاعتماد على شريط حالة يحجز مساحته الخاصة.
    statusBarStyle: 'black-translucent',
    title: APP_NAME,
  },
  other: {
    'mobile-web-app-capable': 'yes',
  },
};

export const viewport: Viewport = {
  width:        'device-width',
  initialScale: 1,
  // FIX PWA-07: maximumScale/userScalable الافتراضي (بدون تحديد) يسمح
  // بالتكبير — لا نمنعه صراحة (يضر بإمكانية الوصول)، لكن viewportFit
  // ضروري لتفعيل env(safe-area-inset-*) في CSS على iOS (الإشعار/الحواف
  // المستديرة).
  viewportFit: 'cover',
  // FIX PWA-12 (cont.) / FIX UX-03: a single static themeColor stayed
  // correct for light mode but went stale the moment dark mode became
  // reachable (ThemeToggle) — the browser chrome/PWA status bar would
  // still show the light-mode olive (#2F5D45) while the app itself had
  // switched to the dark palette's lighter primary. The array form lets
  // Next.js emit both light/dark <meta name="theme-color"> tags with
  // their own media queries, so the chrome always matches whichever
  // .dark or :root --primary is actually active. Hex values computed
  // directly from the same HSL tokens in globals.css (light: 148.7
  // 32.9% 27.5%, dark: 148 38% 52%) — keep these two in sync if the
  // palette ever changes.
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#2F5D45' },
    { media: '(prefers-color-scheme: dark)',  color: '#56B381' },
  ],
};

// ── Layout ────────────────────────────────────────────────────────

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    // FIX UX-03: suppressHydrationWarning is required by next-themes —
    // it sets the `class`/`style` attributes on <html> from
    // localStorage before React hydrates, so the server-rendered
    // markup and the first client render legitimately differ on this
    // one element. Without this, React logs a hydration mismatch
    // warning on every load even though nothing is actually broken.
    <html lang="ar" dir="rtl" suppressHydrationWarning>
      <body>
        <AppProviders>
          {children}
        </AppProviders>
      </body>
    </html>
  );
}
