'use client';
import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input';
import { useMyProducts } from '@/hooks/queries/useProducts'; import { useMyAds } from '@/hooks/queries/useAds'; import { useMyServiceListings } from '@/hooks/queries/useServiceListings'; import { useCreateSale } from '@/hooks/mutations/useSaleMutations'; import { useCustomerSearch } from '@/hooks/queries/useCustomers';
import { MixedPaymentForm, type PaymentPart } from './payments/MixedPaymentForm'; import { InstallmentForm, type InstallmentDraft } from './payments/InstallmentForm';
import type { SaleEntityType, SaleTransferMethod, CreateSalePayload } from '@/types/sale.types'; import type { Product } from '@/types/product.types'; import type { AdListItem } from '@/types/ad.types'; import type { ServiceListing } from '@/types/service.types';
export interface SalePrefill { entityType?:SaleEntityType; entityId?:string; entityTitle?:string; entityImageUrl?:string|null; unitPrice?:number; costPrice?:number|null; storeId?:string; serviceRequestId?:string; buyerName?:string; buyerPhone?:string; }
interface Props { open:boolean; onOpenChange:(open:boolean)=>void; prefill?:SalePrefill|null; }
function Label({children}:{children:ReactNode}){return <span className="text-sm font-medium">{children}</span>}; const num=(v:string|number|undefined|null)=>Number(v??0);
export function AddSaleDialog({open,onOpenChange,prefill}:Props){
 const [entityType,setEntityType]=useState<SaleEntityType>(prefill?.entityType??'PRODUCT'); const [entityId,setEntityId]=useState(prefill?.entityId??''); const [entityTitle,setEntityTitle]=useState(prefill?.entityTitle??''); const [image,setImage]=useState<string|null>(prefill?.entityImageUrl??null); const [storeId,setStoreId]=useState(prefill?.storeId??''); const [quantity,setQuantity]=useState('1'); const [selectedStock,setSelectedStock]=useState<number|null>(null); const [unitPrice,setUnitPrice]=useState(prefill?.unitPrice==null?'':String(prefill.unitPrice)); const [costPrice,setCostPrice]=useState(prefill?.costPrice==null?'':String(prefill.costPrice)); const [buyerName,setBuyerName]=useState(prefill?.buyerName??''); const [buyerPhone,setBuyerPhone]=useState(prefill?.buyerPhone??''); const [customerId,setCustomerId]=useState(''); const [paymentMode,setPaymentMode]=useState<'full'|'partial'|'due'|'installments'>('full'); const [method,setMethod]=useState<SaleTransferMethod>('CASH'); const [payments,setPayments]=useState<PaymentPart[]>([{amount:'',method:'CASH'}]); const [installments,setInstallments]=useState<InstallmentDraft[]>([]); const [note,setNote]=useState('');
 const products=useMyProducts({page:1,limit:100,status:'ACTIVE'},{enabled:open&&entityType==='PRODUCT'}); const ads=useMyAds({page:1,limit:100},{enabled:open&&entityType==='AD'}); const services=useMyServiceListings({page:1,limit:100,status:'ACTIVE'},{enabled:open&&entityType==='SERVICE'}); const search=useCustomerSearch(buyerName||buyerPhone,open); const create=useCreateSale();
 useEffect(()=>{if(!open)return;setEntityType(prefill?.entityType??'PRODUCT');setEntityId(prefill?.entityId??'');setEntityTitle(prefill?.entityTitle??'');setImage(prefill?.entityImageUrl??null);setStoreId(prefill?.storeId??'');setQuantity('1');setSelectedStock(null);setUnitPrice(prefill?.unitPrice==null?'':String(prefill.unitPrice));setCostPrice(prefill?.costPrice==null?'':String(prefill.costPrice));setBuyerName(prefill?.buyerName??'');setBuyerPhone(prefill?.buyerPhone??'');setCustomerId('');setPaymentMode('full');setMethod('CASH');setPayments([{amount:'',method:'CASH'}]);setInstallments([]);setNote('')},[open,prefill]);
 const total=useMemo(()=>Math.round(num(quantity)*num(unitPrice)*100)/100,[quantity,unitPrice]); const mixedTotal=payments.reduce((s,p)=>s+num(p.amount),0); const resolvedPaid=paymentMode==='full'?total:paymentMode==='partial'?Math.min(total,mixedTotal):0; const due=Math.max(0,Math.round((total-resolvedPaid)*100)/100); const installmentsTotal=installments.reduce((s,p)=>s+p.amount,0);
 function selectEntity(id:string){setEntityId(id); if(entityType==='PRODUCT'){const x=(products.data?.items??[]).find((a:Product)=>a.id===id);if(x){setEntityTitle(x.name);setUnitPrice(x.price);setCostPrice(x.costPrice == null ? '' : String(x.costPrice));setSelectedStock(x.stockQuantity ?? null);setImage(x.images?.[0]??null);setStoreId(x.storeId);}} else if(entityType==='AD'){const x=(ads.data?.items??[]).find((a:AdListItem)=>a.id===id);if(x){setEntityTitle(x.title);setUnitPrice(String(x.price));setImage(x.images?.[0]??null);setStoreId('');}} else {const x=(services.data?.items??[]).find((a:ServiceListing)=>a.id===id);if(x){setEntityTitle(x.title);setUnitPrice(x.price??'0');setImage(x.images?.[0]??null);setStoreId('');}} }
 const submit=async()=>{const actualPaid=paymentMode==='full'?total:paymentMode==='partial'?mixedTotal:0; if(actualPaid>total)return; const payload:CreateSalePayload={...(storeId?{storeId}:{}),entityType,...(entityId?{entityId}:{}),entityTitle:entityTitle.trim(),entityImageUrl:image,quantity:Math.max(1,Math.floor(num(quantity))),unitPrice:num(unitPrice),costPrice:costPrice===''?null:num(costPrice),buyerName:buyerName.trim()||'عميل نقدي',buyerPhone:buyerPhone.trim()||null,...(customerId?{customerId}:{}),...(prefill?.serviceRequestId?{serviceRequestId:prefill.serviceRequestId}:{}),paymentStatus:actualPaid>=total?'PAID':actualPaid>0?'PARTIAL':'UNPAID',paidAmount:actualPaid,dueDate:actualPaid<total?new Date(Date.now()+30*86400000).toISOString():null,note:note.trim()||null,...(actualPaid>0?(paymentMode==='partial'?{payments:payments.filter(p=>num(p.amount)>0).map(p=>({amount:num(p.amount),method:p.method,transferRef:p.transferRef}))}:{payment:{amount:actualPaid,method}}):{}),...(paymentMode==='installments'?{installments}: {})}; await create.mutateAsync(payload);onOpenChange(false)};
 const picker=entityType==='PRODUCT'?products.data?.items??[]:entityType==='AD'?ads.data?.items??[]:services.data?.items??[];
 return <Dialog open={open} onOpenChange={v=>{if(!create.isPending)onOpenChange(v)}}><DialogContent className="max-h-[92dvh] overflow-y-auto sm:max-w-2xl" dir="rtl"><DialogHeader><DialogTitle>تسجيل بيع جديد</DialogTitle><DialogDescription>سجّل البيع والدفع والفاتورة من نفس النافذة.</DialogDescription></DialogHeader><div className="space-y-5">
 <div className="grid grid-cols-4 gap-2">{([['PRODUCT','منتج'],['AD','إعلان'],['SERVICE','خدمة'],['FREE','مخصص']] as const).map(([v,l])=><Button key={v} type="button" variant={entityType===v?'default':'outline'} onClick={()=>{setEntityType(v);setEntityId('');setEntityTitle('');setUnitPrice('');setCostPrice('');setSelectedStock(null);setStoreId('');}}>{l}</Button>)}</div>
 {entityType==='FREE'?<div className="space-y-2"><Label>اسم البيع</Label><Input value={entityTitle} onChange={e=>setEntityTitle(e.target.value)} /></div>:<div className="space-y-2"><Label>العنصر</Label><select value={entityId} onChange={e=>selectEntity(e.target.value)} className="h-10 w-full rounded-md border bg-background px-3"><option value="">اختر العنصر</option>{picker.map((x:any)=><option key={x.id} value={x.id}>{x.name??x.title}</option>)}</select></div>}
 <div className="grid grid-cols-2 gap-3"><div><Label>الكمية</Label><Input type="number" min="1" value={quantity} onChange={e=>setQuantity(e.target.value)}/></div><div><Label>سعر الوحدة</Label><Input type="number" min="0" value={unitPrice} onChange={e=>setUnitPrice(e.target.value)}/></div><div><Label>سعر التكلفة</Label><Input type="number" min="0" value={costPrice} onChange={e=>setCostPrice(e.target.value)}/></div><div className="rounded-lg border bg-muted/40 p-3"><span className="text-xs text-muted-foreground">الإجمالي</span><strong className="mt-1 block">{total.toFixed(2)} ₪</strong></div></div>{entityType==='PRODUCT' && selectedStock != null && Number(quantity) > selectedStock ? <p className="col-span-full rounded-lg border border-warning/40 bg-warning/10 p-2 text-xs text-warning-foreground">الكمية المطلوبة أكبر من المخزون الحالي ({selectedStock}). سيتم السماح بالتسجيل، وقد يصبح المخزون سالبًا.</p> : entityType==='PRODUCT' && selectedStock != null && selectedStock <= 5 ? <p className="col-span-full rounded-lg border border-warning/40 bg-warning/10 p-2 text-xs">تنبيه: المتبقي حاليًا {selectedStock} فقط.</p> : null}
 <div className="space-y-3 rounded-xl border p-4"><strong>العميل والدفع</strong><div className="grid gap-3 sm:grid-cols-2"><div className="relative"><Label>العميل</Label><Input value={buyerName} onChange={e=>{setBuyerName(e.target.value);setCustomerId('')}} placeholder="اسم العميل"/>{search.data?.length?<div className="absolute top-full z-20 mt-1 w-full rounded-lg border bg-popover p-1 shadow">{search.data.map(c=><button key={c.id} type="button" className="block w-full p-2 text-start text-sm hover:bg-muted" onClick={()=>{setCustomerId(c.id);setBuyerName(c.name);setBuyerPhone(c.phone??'')}}>{c.name}{c.phone?` · ${c.phone}`:''}</button>)}</div>:null}</div><div><Label>الجوال</Label><Input dir="ltr" value={buyerPhone} onChange={e=>{setBuyerPhone(e.target.value);setCustomerId('')}}/></div></div>
 <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{([['full','كامل'],['partial','جزئي'],['due','آجل'],['installments','تقسيط']] as const).map(([v,l])=><Button key={v} type="button" variant={paymentMode===v?'default':'outline'} onClick={()=>setPaymentMode(v)}>{l}</Button>)}</div>
 {paymentMode==='full'?<div className="grid grid-cols-2 gap-3"><div><Label>طريقة الدفع</Label><select value={method} onChange={e=>setMethod(e.target.value as SaleTransferMethod)} className="h-10 w-full rounded-md border bg-background px-3"><option value="CASH">نقدي</option><option value="JAWWAL_PAY">جوال باي</option><option value="BANK_PALESTINE">بنك فلسطين</option><option value="PALPAY">PalPay</option><option value="CARD">بطاقة</option><option value="OTHER">أخرى</option></select></div><div className="rounded-lg bg-muted/40 p-3 text-sm">المدفوع <strong>{total.toFixed(2)} ₪</strong></div></div>:null}
 {paymentMode==='partial'?<MixedPaymentForm payments={payments} onChange={setPayments} total={total}/>:null}
 {paymentMode==='installments'?<><div className="text-sm">دفعة أولى: 0 ₪ · المتبقي: {total.toFixed(2)} ₪</div><InstallmentForm due={total} onChange={setInstallments}/>{installments.length?<div className="text-xs text-muted-foreground">تم اعتماد {installments.length} أقساط بمجموع {installmentsTotal.toFixed(2)} ₪</div>:null}</>:null}
 <div className="flex justify-between border-t pt-3 text-sm"><span>المتبقي</span><strong>{(paymentMode==='installments'?Math.max(0,total-installmentsTotal):due).toFixed(2)} ₪</strong></div></div>
 <div><Label>ملاحظة</Label><Input value={note} onChange={e=>setNote(e.target.value)}/></div></div><DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>إلغاء</Button><Button disabled={create.isPending||!entityTitle.trim()||total<=0||(paymentMode==='partial'&&(mixedTotal<=0||mixedTotal>total))||(paymentMode==='installments'&&(!installments.length||Math.abs(installmentsTotal-total)>0.009))} onClick={()=>void submit()}>تسجيل البيع</Button></DialogFooter></DialogContent></Dialog>
}
