'use client';
import { useEffect, useMemo, useState } from 'react';
import { Button } from '@/components/ui/button';
import { useReturnSale } from '@/hooks/mutations/useSaleMutations';
import type { SaleRecord } from '@/types/sale.types';
const reasons=[['DAMAGED','معطوب'],['WRONG_ITEM','صنف خاطئ'],['NOT_LIKED','لم يعجبه'],['LATE','متأخر'],['OTHER','أخرى']] as const;
export function ReturnSaleDialog({sale,open,onOpenChange}:{sale:SaleRecord;open:boolean;onOpenChange:(v:boolean)=>void}){
 const returned=(sale.returns??[]).reduce((s,r)=>s+Number((r as {quantity?:number}).quantity??0),0); const max=Math.max(0,sale.quantity-returned); const [qty,setQty]=useState(1); const [reason,setReason]=useState<typeof reasons[number][0]>('DAMAGED'); const [refund,setRefund]=useState(''); const [note,setNote]=useState(''); const [restock,setRestock]=useState(true); const mutation=useReturnSale();
 useEffect(()=>{if(open){setQty(1);setRefund((Number(sale.unitPrice)).toFixed(2));setReason('DAMAGED');setNote('');setRestock(true)}},[open,sale]); const auto=useMemo(()=>Math.min(Number(sale.unitPrice)*qty,Math.max(0,Number(sale.totalPrice)-Number(sale.refundedAmount??0))),[sale,qty]);
 if(!open)return null; return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" dir="rtl"><div className="w-full max-w-md rounded-2xl bg-background p-5 shadow-xl"><h2 className="text-lg font-semibold">تسجيل مرتجع</h2><p className="mt-1 text-sm text-muted-foreground">{sale.entityTitle}</p><div className="mt-4 space-y-3"><label className="block text-sm">الكمية<input className="mt-1 w-full rounded-md border bg-background px-3 py-2" type="number" min={1} max={max} value={qty} onChange={e=>setQty(Math.min(max,Math.max(1,Number(e.target.value)||1)))} /></label><label className="block text-sm">السبب<select className="mt-1 w-full rounded-md border bg-background px-3 py-2" value={reason} onChange={e=>setReason(e.target.value as typeof reason)}>{reasons.map(r=><option key={r[0]} value={r[0]}>{r[1]}</option>)}</select></label><label className="block text-sm">مبلغ الاسترداد<input className="mt-1 w-full rounded-md border bg-background px-3 py-2" type="number" min={0} step="0.01" value={refund} onChange={e=>setRefund(e.target.value)} /></label><p className="text-xs text-muted-foreground">المقترح: {auto.toFixed(2)} ₪</p><label className="block text-sm">ملاحظة<textarea className="mt-1 min-h-20 w-full rounded-md border bg-background px-3 py-2" value={note} onChange={e=>setNote(e.target.value)} /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={restock} onChange={e=>setRestock(e.target.checked)}/> إعادة الكمية إلى المخزون</label></div><div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={()=>onOpenChange(false)}>إلغاء</Button><Button disabled={mutation.isPending||max<1} onClick={()=>mutation.mutate({id:sale.id,payload:{quantity:qty,refundAmount:Number(refund),reason,reasonNote:note||undefined,restockedToInventory:restock}},{onSuccess:()=>onOpenChange(false)})}>{mutation.isPending?'جارٍ الحفظ…':'تسجيل المرتجع'}</Button></div></div></div>;
}
