'use client';
import { Download, FileText, Printer } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Button } from '@/components/ui/button';
import { useSalesReport } from '@/hooks/queries/useSales';
import type { SalePaymentStatus } from '@/types/sale.types';

const money=(n:number)=>Number(n||0).toFixed(2);
const csvEscape=(v:unknown)=>`"${String(v??'').replace(/\"/g, '\"\"')}"`;
export function SalesReports(){
 const [from,setFrom]=useState(''); const [to,setTo]=useState(''); const [status,setStatus]=useState<SalePaymentStatus|''>('');
 const params=useMemo(()=>({from:from||undefined,to:to?`${to}T23:59:59.999`:undefined,status:status||undefined,limit:5000}),[from,to,status]);
 const {data,isLoading,isError}=useSalesReport(params);
 const download=()=>{if(!data)return; const header=['الفاتورة','التاريخ','العميل','المتجر','الوصف','الكمية','الإيراد','التكلفة','الربح','المدفوع','المتبقي','المرتجع','الحالة']; const body=data.rows.map(r=>[r.invoiceNumber,r.soldAt,r.buyerName,r.storeName,r.title,r.quantity,money(r.revenue),money(r.cost),money(r.profit),money(r.paid),money(r.due),money(r.refunded),r.status]); const csv='\uFEFF'+[header,...body].map(row=>row.map(csvEscape).join(',')).join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})); a.download=`sales-report-${new Date().toISOString().slice(0,10)}.csv`; a.click(); URL.revokeObjectURL(a.href);};
 return <section className="space-y-4" dir="rtl"><div className="print:hidden flex flex-wrap items-end gap-3 rounded-xl border bg-card p-4"><label className="text-sm">من<input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="mt-1 block rounded-lg border bg-background px-3 py-2"/></label><label className="text-sm">إلى<input type="date" value={to} onChange={e=>setTo(e.target.value)} className="mt-1 block rounded-lg border bg-background px-3 py-2"/></label><label className="text-sm">الحالة<select value={status} onChange={e=>setStatus(e.target.value as SalePaymentStatus|'')} className="mt-1 block rounded-lg border bg-background px-3 py-2"><option value="">الكل</option><option value="PAID">مدفوع</option><option value="PARTIAL">جزئي</option><option value="UNPAID">غير مدفوع</option><option value="OVERDUE">متأخر</option></select></label><div className="ms-auto flex gap-2"><Button variant="outline" onClick={()=>window.print()}><Printer className="ms-2 h-4 w-4"/>PDF / طباعة</Button><Button onClick={download} disabled={!data}><Download className="ms-2 h-4 w-4"/>CSV</Button></div></div>
 {isLoading?<div className="h-64 animate-pulse rounded-xl border bg-muted/40"/>:isError?<div className="rounded-xl border p-6 text-center text-destructive">تعذر تحميل التقرير.</div>:data&&<><div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[['الإيراد',data.totals.revenue],['التكلفة',data.totals.cost],['الربح',data.totals.profit],['المدفوع',data.totals.paid],['المتبقي',data.totals.due],['المرتجع',data.totals.refunded]].map(([k,v])=><div key={String(k)} className="rounded-xl border bg-card p-3"><div className="text-xs text-muted-foreground">{k}</div><div className="mt-1 font-bold">{money(Number(v))} ₪</div></div>)}</div><div className="overflow-x-auto rounded-xl border bg-card"><table className="w-full min-w-[900px] text-sm"><thead className="bg-muted/50 text-right"><tr>{['الفاتورة','التاريخ','العميل','المنتج','الإيراد','التكلفة','الربح','المدفوع','المتبقي'].map(h=><th key={h} className="px-3 py-3">{h}</th>)}</tr></thead><tbody>{data.rows.map(r=><tr key={r.id} className="border-t"><td className="px-3 py-3 font-medium">{r.invoiceNumber??'—'}</td><td className="px-3 py-3">{new Date(r.soldAt).toLocaleDateString('ar-PS')}</td><td className="px-3 py-3">{r.buyerName}</td><td className="px-3 py-3">{r.title}</td><td className="px-3 py-3">{money(r.revenue)}</td><td className="px-3 py-3">{money(r.cost)}</td><td className="px-3 py-3 font-semibold">{money(r.profit)}</td><td className="px-3 py-3">{money(r.paid)}</td><td className="px-3 py-3">{money(r.due)}</td></tr>)}</tbody></table></div></>}{!isLoading&&!data?.rows.length&&<div className="rounded-xl border border-dashed p-8 text-center text-muted-foreground"><FileText className="mx-auto h-8 w-8"/><p className="mt-2">لا توجد عمليات ضمن الفلتر.</p></div>}</section>;
}
