'use client';
import { useQuery } from '@tanstack/react-query';
import Link from 'next/link';
import { BadgeCheck, BarChart3, MessageCircle, Star } from 'lucide-react';
import { apiClient } from '@/api/client';
import { useStartConversation } from '@/hooks/mutations/useConversationMutations';
import { useRouter } from 'next/navigation';
import type { ApiResponse } from '@/types/api.types';

type Stats={storeId:string;storeName:string;storeSlug:string;ownerUserId:string;totalSales:number;averageRating:number;reviewCount:number;verifiedSeller:boolean;lastSaleAt:string|null};
export function PublicSalesStats({slug}:{slug:string}){const router=useRouter(); const startConversation=useStartConversation(); const {data,isLoading,isError}=useQuery({queryKey:['public-store-sales-stats',slug],queryFn:()=>apiClient.get<ApiResponse<Stats>>(`/public/stores/${encodeURIComponent(slug)}/stats`).then(r=>r.data.data)}); if(isLoading)return <div className="h-64 animate-pulse rounded-2xl border bg-muted/40"/>; if(isError||!data)return <div className="rounded-2xl border p-8 text-center text-sm text-muted-foreground">تعذر تحميل إحصائيات المتجر.</div>; return <section className="mx-auto w-full max-w-3xl space-y-5" dir="rtl"><div className="rounded-2xl border bg-card p-5"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary/10 text-primary"><BarChart3/></div><div className="min-w-0 flex-1"><h1 className="text-xl font-bold">{data.storeName}</h1><div className="mt-1 flex flex-wrap gap-2 text-xs text-muted-foreground">{data.verifiedSeller?<span className="inline-flex items-center gap-1 text-primary"><BadgeCheck className="h-4 w-4"/>بائع موثّق</span>:null}<span className="inline-flex items-center gap-1"><Star className="h-4 w-4"/> {data.averageRating.toFixed(1)} ({data.reviewCount} تقييم)</span></div></div></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="rounded-xl bg-muted/40 p-4"><p className="text-xs text-muted-foreground">إجمالي المبيعات</p><p className="mt-1 text-xl font-bold">{data.totalSales.toLocaleString('ar-PS')}</p></div><div className="rounded-xl bg-muted/40 p-4"><p className="text-xs text-muted-foreground">التقييم</p><p className="mt-1 text-xl font-bold">{data.averageRating.toFixed(1)} ★</p></div><div className="rounded-xl bg-muted/40 p-4"><p className="text-xs text-muted-foreground">آخر مبيعة</p><p className="mt-1 text-sm font-semibold">{data.lastSaleAt?new Date(data.lastSaleAt).toLocaleDateString('ar-PS', { timeZone: 'Asia/Gaza' }):'لا توجد'}</p></div></div><div className="mt-5 flex flex-wrap gap-2"><Link href={`/stores/${data.storeId}`} className="rounded-lg border px-4 py-2 text-sm">عرض المتجر</Link><button type="button" onClick={()=>startConversation.mutate({userId:data.ownerUserId},{onSuccess:(c)=>{ if(c?.id) router.push(`/messages/${c.id}`); }})} disabled={startConversation.isPending} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm text-primary-foreground disabled:opacity-60"><MessageCircle className="h-4 w-4"/>{startConversation.isPending?'جاري الفتح…':'تواصل مع البائع'}</button></div></div></section>}
