-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'SERVICE_REQUEST_NEW';
ALTER TYPE "NotificationType" ADD VALUE 'SERVICE_REQUEST_UPDATE';
ALTER TYPE "NotificationType" ADD VALUE 'APPOINTMENT_UPDATE';
