'use client';
import { HydrationSafeRelativeTime } from '@/components/shared/HydrationSafeRelativeTime';
import { memo } from 'react';
import { Pause, Trash2 } from 'lucide-react';
import { Button } from '@/components/shared/ui/Button';
import { Badge } from '@/components/shared/ui/Badge';
import { formatPrice } from '@/lib/formatters';
type Product=Record<string,unknown>;
type Props={product:Product; pendingStatusId?:string; onPause:(id:string)=>void; onDelete:(id:string,name:string)=>void};
export const AdminProductRow=memo(function AdminProductRow({product,pendingStatusId,onPause,onDelete}:Props){const id=String(product.id),name=String(product.name),status=String(product.status),store=product.store as {name?:string}|undefined;return <tr key={id} className="hover:bg-muted/30 [content-visibility:auto] [contain-intrinsic-size:auto_56px]"><td className="p-3 font-medium">{name}</td><td className="p-3 text-muted-foreground">{store?.name??'—'}</td><td className="p-3 tabular-nums">{formatPrice(Number(product.price))}</td><td className="p-3"><Badge variant={status==='ACTIVE'?'success':'secondary'}>{status}</Badge></td><td className="p-3 text-xs text-muted-foreground">{<HydrationSafeRelativeTime date={String(product.createdAt)} />}</td><td className="p-3"><div className="flex gap-1">{status==='ACTIVE'&&<Button type="button" size="sm" variant="ghost" aria-label={`إيقاف المنتج ${name}`} onClick={()=>onPause(id)} disabled={pendingStatusId===id}><Pause className="h-4 w-4"/></Button>}{status!=='DELETED'&&<Button type="button" size="sm" variant="ghost" className="text-destructive" aria-label={`حذف المنتج ${name}`} onClick={()=>onDelete(id,name)}><Trash2 className="h-4 w-4"/></Button>}</div></td></tr>});
